const filler_header = ["index", "trial_code", "sentence", "status", "target", "target_filename", "competitor", "competitor_filename", "Distractor1", "Distractor1_filename", "Distractor2", "Distractor2_filename", "Distractor3", "Distractor3_filename", "audio_tag"]

const filler_trials = {
	pred_ant: {
		index: "21",
		trial_code: "pred_ant",
		sentence: "A termite looks like an ant",
		status: "filler",
		target: "ant",
		target_filename: "PICTURE_585.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "saxophone",
		Distractor1_filename: "PICTURE_107.png",
		Distractor2: "trigger",
		Distractor2_filename: "PICTURE_291.png",
		Distractor3: "box",
		Distractor3_filename: "PICTURE_508.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_ant_2_AnF.wav"
	},
	pred_belt: {
		index: "22",
		trial_code: "pred_belt",
		sentence: "His pants were held up by a belt",
		status: "filler",
		target: "belt",
		target_filename: "PICTURE_165.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "green house",
		Distractor1_filename: "PICTURE_106.png",
		Distractor2: "plumber",
		Distractor2_filename: "PICTURE_294.png",
		Distractor3: "fox",
		Distractor3_filename: "PICTURE_521.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_belt_2_AnF.wav"
	},
	pred_bench: {
		index: "23",
		trial_code: "pred_bench",
		sentence: "The judge is sitting on the bench",
		status: "filler",
		target: "bench",
		target_filename: "PICTURE_449.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "deer",
		Distractor1_filename: "PICTURE_105.png",
		Distractor2: "mime",
		Distractor2_filename: "PICTURE_303.png",
		Distractor3: "telephone",
		Distractor3_filename: "PICTURE_509.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_bench_1_AnF.wav"
	},
	pred_bomb: {
		index: "24",
		trial_code: "pred_bomb",
		sentence: "The airplane dropped a bomb",
		status: "filler",
		target: "bomb",
		target_filename: "PICTURE_386.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "nose",
		Distractor1_filename: "PICTURE_100.png",
		Distractor2: "tunnel",
		Distractor2_filename: "PICTURE_286.png",
		Distractor3: "shepherd",
		Distractor3_filename: "PICTURE_502.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_bomb_2_AnF.wav"
	},
	pred_bone: {
		index: "25",
		trial_code: "pred_bone",
		sentence: "The dog chewed on a bone",
		status: "filler",
		target: "bone",
		target_filename: "PICTURE_24.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "mask",
		Distractor1_filename: "PICTURE_84.png",
		Distractor2: "knot",
		Distractor2_filename: "PICTURE_267.png",
		Distractor3: "sun",
		Distractor3_filename: "PICTURE_488.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_bone_2_AnF.wav"
	},
	pred_broom: {
		index: "26",
		trial_code: "pred_broom",
		sentence: "The girl swept the floor with a broom",
		status: "filler",
		target: "broom",
		target_filename: "PICTURE_590.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "tiger",
		Distractor1_filename: "PICTURE_98.png",
		Distractor2: "cape",
		Distractor2_filename: "PICTURE_275.png",
		Distractor3: "avocado",
		Distractor3_filename: "PICTURE_477.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_broom_1_AnF.wav"
	},
	pred_carrot: {
		index: "27",
		trial_code: "pred_carrot",
		sentence: "The rabbit ate the orange carrot",
		status: "filler",
		target: "carrot",
		target_filename: "PICTURE_285.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "heart",
		Distractor1_filename: "PICTURE_83.png",
		Distractor2: "lizard",
		Distractor2_filename: "PICTURE_252.png",
		Distractor3: "circle",
		Distractor3_filename: "PICTURE_496.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_carrot_2_AnF.wav"
	},
	pred_castle: {
		index: "28",
		trial_code: "pred_castle",
		sentence: "The queen lives inside of the castle",
		status: "filler",
		target: "castle",
		target_filename: "PICTURE_240.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "bag",
		Distractor1_filename: "PICTURE_53.png",
		Distractor2: "root",
		Distractor2_filename: "PICTURE_245.png",
		Distractor3: "pineapple",
		Distractor3_filename: "PICTURE_442.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_castle_1_AnF.wav"
	},
	pred_cheese: {
		index: "29",
		trial_code: "pred_cheese",
		sentence: "He paired the red wine with cheese",
		status: "filler",
		target: "cheese",
		target_filename: "PICTURE_72.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "wasp",
		Distractor1_filename: "PICTURE_62.png",
		Distractor2: "brain",
		Distractor2_filename: "PICTURE_247.png",
		Distractor3: "apron",
		Distractor3_filename: "PICTURE_476.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_cheese_2_AnF.wav"
	},
	pred_chest: {
		index: "30",
		trial_code: "pred_chest",
		sentence: "The doctor X-rayed his chest",
		status: "filler",
		target: "chest",
		target_filename: "PICTURE_231.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "feather",
		Distractor1_filename: "PICTURE_97.png",
		Distractor2: "pomegranate",
		Distractor2_filename: "PICTURE_281.png",
		Distractor3: "shoe",
		Distractor3_filename: "PICTURE_541.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_chest_2_AnF.wav"
	},
	pred_coin: {
		index: "31",
		trial_code: "pred_coin",
		sentence: "Let's decide by tossing a coin",
		status: "filler",
		target: "coin",
		target_filename: "PICTURE_383.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "park",
		Distractor1_filename: "PICTURE_82.png",
		Distractor2: "baguette",
		Distractor2_filename: "PICTURE_258.png",
		Distractor3: "shield",
		Distractor3_filename: "PICTURE_501.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_coin_2_AnF.wav"
	},
	pred_computer: {
		index: "32",
		trial_code: "pred_computer",
		sentence: "She started typing on the computer",
		status: "filler",
		target: "computer",
		target_filename: "PICTURE_196.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "saw",
		Distractor1_filename: "PICTURE_52.png",
		Distractor2: "light bulb",
		Distractor2_filename: "PICTURE_244.png",
		Distractor3: "sausage",
		Distractor3_filename: "PICTURE_441.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_computer_2_AnF.wav"
	},
	pred_cork: {
		index: "33",
		trial_code: "pred_cork",
		sentence: "The bottle was sealed with a cork",
		status: "filler",
		target: "cork",
		target_filename: "PICTURE_409.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "fruit",
		Distractor1_filename: "PICTURE_114.png",
		Distractor2: "envelope",
		Distractor2_filename: "PICTURE_310.png",
		Distractor3: "turtle",
		Distractor3_filename: "PICTURE_531.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_cork_1_AnF.wav"
	},
	pred_crown: {
		index: "34",
		trial_code: "pred_crown",
		sentence: "The king wore a golden crown",
		status: "filler",
		target: "crown",
		target_filename: "PICTURE_32.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "milk",
		Distractor1_filename: "PICTURE_96.png",
		Distractor2: "drum",
		Distractor2_filename: "PICTURE_278.png",
		Distractor3: "squirrel",
		Distractor3_filename: "PICTURE_484.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_crown_2_AnF.wav"
	},
	pred_dentist: {
		index: "35",
		trial_code: "pred_dentist",
		sentence: "Her tooth hurt so she went to the dentist",
		status: "filler",
		target: "dentist",
		target_filename: "PICTURE_246.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "broccoli",
		Distractor1_filename: "PICTURE_76.png",
		Distractor2: "lamppost",
		Distractor2_filename: "PICTURE_261.png",
		Distractor3: "stairs",
		Distractor3_filename: "PICTURE_500.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_dentist_1_AnF.wav"
	},
	pred_fist: {
		index: "36",
		trial_code: "pred_fist",
		sentence: "He hit me with a clenched fist",
		status: "filler",
		target: "fist",
		target_filename: "PICTURE_411.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "painting",
		Distractor1_filename: "PICTURE_99.png",
		Distractor2: "wig",
		Distractor2_filename: "PICTURE_277.png",
		Distractor3: "skunk",
		Distractor3_filename: "PICTURE_493.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_fist_1_AnF.wav"
	},
	pred_fork: {
		index: "37",
		trial_code: "pred_fork",
		sentence: "He eats the salad with a fork",
		status: "filler",
		target: "fork",
		target_filename: "PICTURE_673.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "camel",
		Distractor1_filename: "PICTURE_77.png",
		Distractor2: "island",
		Distractor2_filename: "PICTURE_260.png",
		Distractor3: "basket",
		Distractor3_filename: "PICTURE_487.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_fork_1_AnF.wav"
	},
	pred_jar: {
		index: "38",
		trial_code: "pred_jar",
		sentence: "The cookies were kept in a jar",
		status: "filler",
		target: "jar",
		target_filename: "PICTURE_448.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "lung",
		Distractor1_filename: "PICTURE_112.png",
		Distractor2: "ostrich",
		Distractor2_filename: "PICTURE_299.png",
		Distractor3: "violin",
		Distractor3_filename: "PICTURE_566.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_jar_2_AnF.wav"
	},
	pred_knife: {
		index: "39",
		trial_code: "pred_knife",
		sentence: "I cut my finger with a knife",
		status: "filler",
		target: "knife",
		target_filename: "PICTURE_465.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "hippopotamus",
		Distractor1_filename: "PICTURE_115.png",
		Distractor2: "flower",
		Distractor2_filename: "PICTURE_312.png",
		Distractor3: "astronaut",
		Distractor3_filename: "PICTURE_539.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_knife_2_AnF.wav"
	},
	pred_lamp: {
		index: "40",
		trial_code: "pred_lamp",
		sentence: "It's getting dark, so light the lamp",
		status: "filler",
		target: "lamp",
		target_filename: "PICTURE_414.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "drum set",
		Distractor1_filename: "PICTURE_101.png",
		Distractor2: "rhinoceros",
		Distractor2_filename: "PICTURE_282.png",
		Distractor3: "tongue",
		Distractor3_filename: "PICTURE_503.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_lamp_2_AnF.wav"
	},
	pred_map: {
		index: "41",
		trial_code: "pred_map",
		sentence: "We're lost so let's look at the map",
		status: "filler",
		target: "map",
		target_filename: "PICTURE_677.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "robot",
		Distractor1_filename: "PICTURE_87.png",
		Distractor2: "hand",
		Distractor2_filename: "PICTURE_264.png",
		Distractor3: "chicken",
		Distractor3_filename: "PICTURE_454.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_map_2_AnF.wav"
	},
	pred_meat: {
		index: "42",
		trial_code: "pred_meat",
		sentence: "He is a vegetarian so he won't eat meat",
		status: "filler",
		target: "meat",
		target_filename: "PICTURE_81.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "wave",
		Distractor1_filename: "PICTURE_73.png",
		Distractor2: "choir",
		Distractor2_filename: "PICTURE_253.png",
		Distractor3: "tank",
		Distractor3_filename: "PICTURE_621.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_meat_2_AnF.wav"
	},
	pred_microphone: {
		index: "43",
		trial_code: "pred_microphone",
		sentence: "The musician sang into the microphone",
		status: "filler",
		target: "microphone",
		target_filename: "PICTURE_208.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "shadow",
		Distractor1_filename: "PICTURE_55.png",
		Distractor2: "pirate",
		Distractor2_filename: "PICTURE_265.png",
		Distractor3: "fly",
		Distractor3_filename: "PICTURE_462.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_microphone_2_AnF.wav"
	},
	pred_mirror: {
		index: "44",
		trial_code: "pred_mirror",
		sentence: "He saw his reflection in the mirror",
		status: "filler",
		target: "mirror",
		target_filename: "PICTURE_340.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "tractor",
		Distractor1_filename: "PICTURE_74.png",
		Distractor2: "potato",
		Distractor2_filename: "PICTURE_249.png",
		Distractor3: "coffin",
		Distractor3_filename: "PICTURE_497.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_mirror_2_AnF.wav"
	},
	pred_mouse: {
		index: "45",
		trial_code: "pred_mouse",
		sentence: "They played a game of cat and mouse",
		status: "filler",
		target: "mouse",
		target_filename: "PICTURE_1.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "fire",
		Distractor1_filename: "PICTURE_116.png",
		Distractor2: "wing",
		Distractor2_filename: "PICTURE_307.png",
		Distractor3: "clown",
		Distractor3_filename: "PICTURE_532.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_mouse_2_AnF.wav"
	},
	pred_net: {
		index: "46",
		trial_code: "pred_net",
		sentence: "He caught the fish in his net",
		status: "filler",
		target: "net",
		target_filename: "PICTURE_346.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "chair",
		Distractor1_filename: "PICTURE_122.png",
		Distractor2: "razor",
		Distractor2_filename: "PICTURE_311.png",
		Distractor3: "lighthouse",
		Distractor3_filename: "PICTURE_540.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_net_2_AnF.wav"
	},
	pred_orchestra: {
		index: "47",
		trial_code: "pred_orchestra",
		sentence: "He is a violinist in the orchestra",
		status: "filler",
		target: "orchestra",
		target_filename: "PICTURE_70.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "ball",
		Distractor1_filename: "PICTURE_732.png",
		Distractor2: "salt",
		Distractor2_filename: "PICTURE_233.png",
		Distractor3: "wardrobe",
		Distractor3_filename: "PICTURE_458.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_orchestra_2_AnF.wav"
	},
	pred_pool: {
		index: "48",
		trial_code: "pred_pool",
		sentence: "The swimmer dove into the pool",
		status: "filler",
		target: "pool",
		target_filename: "PICTURE_362.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "elevator",
		Distractor1_filename: "PICTURE_104.png",
		Distractor2: "birdcage",
		Distractor2_filename: "PICTURE_290.png",
		Distractor3: "face",
		Distractor3_filename: "PICTURE_510.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_pool_1_AnF.wav"
	},
	pred_rope: {
		index: "49",
		trial_code: "pred_rope",
		sentence: "He tossed the drowning man a rope",
		status: "filler",
		target: "rope",
		target_filename: "PICTURE_517.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "moon",
		Distractor1_filename: "PICTURE_90.png",
		Distractor2: "chameleon",
		Distractor2_filename: "PICTURE_269.png",
		Distractor3: "pizza",
		Distractor3_filename: "PICTURE_489.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_rope_2_AnF.wav"
	},
	pred_rug: {
		index: "50",
		trial_code: "pred_rug",
		sentence: "She hated to vacuum the rug",
		status: "filler",
		target: "rug",
		target_filename: "PICTURE_491.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "calendar",
		Distractor1_filename: "PICTURE_108.png",
		Distractor2: "dinosaur",
		Distractor2_filename: "PICTURE_293.png",
		Distractor3: "lips",
		Distractor3_filename: "PICTURE_513.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_rug_1_AnF.wav"
	},
	pred_scissors: {
		index: "51",
		trial_code: "pred_scissors",
		sentence: "He cut the papers with scissors",
		status: "filler",
		target: "scissors",
		target_filename: "PICTURE_453.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "hunter",
		Distractor1_filename: "PICTURE_16.png",
		Distractor2: "plate",
		Distractor2_filename: "PICTURE_234.png",
		Distractor3: "foot",
		Distractor3_filename: "PICTURE_455.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_scissors_1_AnF.wav"
	},
	pred_sheep: {
		index: "52",
		trial_code: "pred_sheep",
		sentence: "The shepherd watched his flock of sheep",
		status: "filler",
		target: "sheep",
		target_filename: "PICTURE_636.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "maze",
		Distractor1_filename: "PICTURE_121.png",
		Distractor2: "ice cream",
		Distractor2_filename: "PICTURE_309.png",
		Distractor3: "branch",
		Distractor3_filename: "PICTURE_536.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_sheep_2_AnF.wav"
	},
	pred_skirt: {
		index: "53",
		trial_code: "pred_skirt",
		sentence: "She shortened the hem of her skirt",
		status: "filler",
		target: "skirt",
		target_filename: "PICTURE_199.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "crutch",
		Distractor1_filename: "PICTURE_88.png",
		Distractor2: "bed",
		Distractor2_filename: "PICTURE_268.png",
		Distractor3: "oil",
		Distractor3_filename: "PICTURE_456.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_skirt_2_AnF.wav"
	},
	pred_sponge: {
		index: "54",
		trial_code: "pred_sponge",
		sentence: "He wiped the sink with a sponge",
		status: "filler",
		target: "sponge",
		target_filename: "PICTURE_650.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "hair",
		Distractor1_filename: "PICTURE_102.png",
		Distractor2: "forest",
		Distractor2_filename: "PICTURE_288.png",
		Distractor3: "underwear",
		Distractor3_filename: "PICTURE_545.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_sponge_1_AnF.wav"
	},
	pred_spoon: {
		index: "55",
		trial_code: "pred_spoon",
		sentence: "Stir your coffee with a spoon",
		status: "filler",
		target: "spoon",
		target_filename: "PICTURE_564.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "helicopter",
		Distractor1_filename: "PICTURE_80.png",
		Distractor2: "butcher",
		Distractor2_filename: "PICTURE_254.png",
		Distractor3: "lightning",
		Distractor3_filename: "PICTURE_506.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_spoon_1_AnF.wav"
	},
	pred_stamp: {
		index: "56",
		trial_code: "pred_stamp",
		sentence: "Air mail requires a special stamp",
		status: "filler",
		target: "stamp",
		target_filename: "PICTURE_57.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "lake",
		Distractor1_filename: "PICTURE_113.png",
		Distractor2: "die",
		Distractor2_filename: "PICTURE_308.png",
		Distractor3: "fingerprint",
		Distractor3_filename: "PICTURE_537.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_stamp_2_AnF.wav"
	},
	pred_swan: {
		index: "57",
		trial_code: "pred_swan",
		sentence: "The duck swam with the white swan",
		status: "filler",
		target: "swan",
		target_filename: "PICTURE_528.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "mouth",
		Distractor1_filename: "PICTURE_91.png",
		Distractor2: "limo",
		Distractor2_filename: "PICTURE_283.png",
		Distractor3: "calculator",
		Distractor3_filename: "PICTURE_516.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_swan_1_AnF.wav"
	},
	pred_sword: {
		index: "58",
		trial_code: "pred_sword",
		sentence: "He killed the dragon with his sword",
		status: "filler",
		target: "sword",
		target_filename: "PICTURE_301.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "river",
		Distractor1_filename: "PICTURE_86.png",
		Distractor2: "heel",
		Distractor2_filename: "PICTURE_266.png",
		Distractor3: "pig",
		Distractor3_filename: "PICTURE_446.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_sword_2_AnF.wav"
	},
	pred_thermometer: {
		index: "59",
		trial_code: "pred_thermometer",
		sentence: "She took her temperature with a thermometer",
		status: "filler",
		target: "thermometer",
		target_filename: "PICTURE_192.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "banana",
		Distractor1_filename: "PICTURE_69.png",
		Distractor2: "wagon",
		Distractor2_filename: "PICTURE_248.png",
		Distractor3: "pyramid",
		Distractor3_filename: "PICTURE_457.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_thermometer_1_AnF.wav"
	},
	pred_truck: {
		index: "60",
		trial_code: "pred_truck",
		sentence: "We shipped the furniture by truck",
		status: "filler",
		target: "truck",
		target_filename: "PICTURE_535.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "seal",
		Distractor1_filename: "PICTURE_92.png",
		Distractor2: "arrow",
		Distractor2_filename: "PICTURE_270.png",
		Distractor3: "kangaroo",
		Distractor3_filename: "PICTURE_479.png",
		audio_tag: "2",
		audio_filename: "AnF/pred_truck_2_AnF.wav"
	},
	pred_tub: {
		index: "61",
		trial_code: "pred_tub",
		sentence: "Paul took a bath in the tub",
		status: "filler",
		target: "tub",
		target_filename: "PICTURE_747.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "desk",
		Distractor1_filename: "PICTURE_110.png",
		Distractor2: "flag",
		Distractor2_filename: "PICTURE_295.png",
		Distractor3: "walrus",
		Distractor3_filename: "PICTURE_529.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_tub_1_AnF.wav"
	},
	pred_turkey: {
		index: "62",
		trial_code: "pred_turkey",
		sentence: "On Thanksgiving his family eats turkey",
		status: "filler",
		target: "turkey",
		target_filename: "PICTURE_668.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "balloon",
		Distractor1_filename: "PICTURE_75.png",
		Distractor2: "shovel",
		Distractor2_filename: "PICTURE_255.png",
		Distractor3: "rose",
		Distractor3_filename: "PICTURE_480.png",
		audio_tag: "1",
		audio_filename: "AnF/pred_turkey_1_AnF.wav"
	},
	unpred_asparagus: {
		index: "63",
		trial_code: "unpred_asparagus",
		sentence: "We're speaking about the asparagus",
		status: "filler",
		target: "asparagus",
		target_filename: "PICTURE_581.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "bullet",
		Distractor1_filename: "PICTURE_155.png",
		Distractor2: "car",
		Distractor2_filename: "PICTURE_358.png",
		Distractor3: "toad",
		Distractor3_filename: "PICTURE_584.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_asparagus_2_AnF.wav"
	},
	unpred_baby: {
		index: "64",
		trial_code: "unpred_baby",
		sentence: "I want to speak about the baby",
		status: "filler",
		target: "baby",
		target_filename: "PICTURE_507.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "road",
		Distractor1_filename: "PICTURE_164.png",
		Distractor2: "gorilla",
		Distractor2_filename: "PICTURE_380.png",
		Distractor3: "cloud",
		Distractor3_filename: "PICTURE_599.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_baby_2_AnF.wav"
	},
	unpred_battery: {
		index: "65",
		trial_code: "unpred_battery",
		sentence: "Bill heard we talked about the battery",
		status: "filler",
		target: "battery",
		target_filename: "PICTURE_656.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "faucet",
		Distractor1_filename: "PICTURE_140.png",
		Distractor2: "night",
		Distractor2_filename: "PICTURE_342.png",
		Distractor3: "cucumber",
		Distractor3_filename: "PICTURE_559.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_battery_1_AnF.wav"
	},
	unpred_beard: {
		index: "66",
		trial_code: "unpred_beard",
		sentence: "Jane did not speak about the beard",
		status: "filler",
		target: "beard",
		target_filename: "PICTURE_159.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "rain",
		Distractor1_filename: "PICTURE_190.png",
		Distractor2: "steering wheel",
		Distractor2_filename: "PICTURE_398.png",
		Distractor3: "cactus",
		Distractor3_filename: "PICTURE_640.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_beard_2_AnF.wav"
	},
	unpred_boat: {
		index: "67",
		trial_code: "unpred_boat",
		sentence: "The man should discuss the boat",
		status: "filler",
		target: "boat",
		target_filename: "PICTURE_482.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "pharmacy",
		Distractor1_filename: "PICTURE_173.png",
		Distractor2: "chain",
		Distractor2_filename: "PICTURE_391.png",
		Distractor3: "sweater",
		Distractor3_filename: "PICTURE_607.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_boat_2_AnF.wav"
	},
	unpred_book: {
		index: "68",
		trial_code: "unpred_book",
		sentence: "I should have considered the book",
		status: "filler",
		target: "book",
		target_filename: "PICTURE_505.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "goal",
		Distractor1_filename: "PICTURE_170.png",
		Distractor2: "strawberry",
		Distractor2_filename: "PICTURE_381.png",
		Distractor3: "dynamite",
		Distractor3_filename: "PICTURE_634.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_book_2_AnF.wav"
	},
	unpred_boy: {
		index: "69",
		trial_code: "unpred_boy",
		sentence: "Ruth must have known about the boy",
		status: "filler",
		target: "boy",
		target_filename: "PICTURE_499.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "parrot",
		Distractor1_filename: "PICTURE_172.png",
		Distractor2: "stapler",
		Distractor2_filename: "PICTURE_387.png",
		Distractor3: "cemetery",
		Distractor3_filename: "PICTURE_603.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_boy_1_AnF.wav"
	},
	unpred_bridge: {
		index: "70",
		trial_code: "unpred_bridge",
		sentence: "Tom will discuss the bridge",
		status: "filler",
		target: "bridge",
		target_filename: "PICTURE_178.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "soccer ball",
		Distractor1_filename: "PICTURE_185.png",
		Distractor2: "teapot",
		Distractor2_filename: "PICTURE_392.png",
		Distractor3: "pelican",
		Distractor3_filename: "PICTURE_662.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_bridge_1_AnF.wav"
	},
	unpred_bus: {
		index: "71",
		trial_code: "unpred_bus",
		sentence: "Jane wants to speak about the bus",
		status: "filler",
		target: "bus",
		target_filename: "PICTURE_273.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "rat",
		Distractor1_filename: "PICTURE_137.png",
		Distractor2: "tomato",
		Distractor2_filename: "PICTURE_326.png",
		Distractor3: "eyebrow",
		Distractor3_filename: "PICTURE_578.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_bus_1_AnF.wav"
	},
	unpred_chocolate: {
		index: "72",
		trial_code: "unpred_chocolate",
		sentence: "He can't consider the chocolate",
		status: "filler",
		target: "chocolate",
		target_filename: "PICTURE_593.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "puddle",
		Distractor1_filename: "PICTURE_150.png",
		Distractor2: "butterfly",
		Distractor2_filename: "PICTURE_351.png",
		Distractor3: "juggler",
		Distractor3_filename: "PICTURE_572.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_chocolate_2_AnF.wav"
	},
	unpred_city: {
		index: "73",
		trial_code: "unpred_city",
		sentence: "Bill can't have considered the city",
		status: "filler",
		target: "city",
		target_filename: "PICTURE_187.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "engine",
		Distractor1_filename: "PICTURE_186.png",
		Distractor2: "fig",
		Distractor2_filename: "PICTURE_397.png",
		Distractor3: "soap",
		Distractor3_filename: "PICTURE_619.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_city_2_AnF.wav"
	},
	unpred_coat: {
		index: "74",
		trial_code: "unpred_coat",
		sentence: "I was considering the coat",
		status: "filler",
		target: "coat",
		target_filename: "PICTURE_644.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "doll",
		Distractor1_filename: "PICTURE_128.png",
		Distractor2: "leaf",
		Distractor2_filename: "PICTURE_318.png",
		Distractor3: "shark",
		Distractor3_filename: "PICTURE_533.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_coat_2_AnF.wav"
	},
	unpred_coffee: {
		index: "75",
		trial_code: "unpred_coffee",
		sentence: "We would consider the coffee",
		status: "filler",
		target: "coffee",
		target_filename: "PICTURE_666.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "sunflower",
		Distractor1_filename: "PICTURE_141.png",
		Distractor2: "lock",
		Distractor2_filename: "PICTURE_349.png",
		Distractor3: "vulture",
		Distractor3_filename: "PICTURE_563.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_coffee_1_AnF.wav"
	},
	unpred_door: {
		index: "76",
		trial_code: "unpred_door",
		sentence: "The man could consider the door",
		status: "filler",
		target: "door",
		target_filename: "PICTURE_546.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "tie",
		Distractor1_filename: "PICTURE_161.png",
		Distractor2: "hedgehog",
		Distractor2_filename: "PICTURE_365.png",
		Distractor3: "lettuce",
		Distractor3_filename: "PICTURE_592.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_door_2_AnF.wav"
	},
	unpred_fence: {
		index: "77",
		trial_code: "unpred_fence",
		sentence: "Bob could have known about the fence",
		status: "filler",
		target: "fence",
		target_filename: "PICTURE_530.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "coconut",
		Distractor1_filename: "PICTURE_163.png",
		Distractor2: "scorpion",
		Distractor2_filename: "PICTURE_370.png",
		Distractor3: "window",
		Distractor3_filename: "PICTURE_597.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_fence_2_AnF.wav"
	},
	unpred_fridge: {
		index: "78",
		trial_code: "unpred_fridge",
		sentence: "You heard Jane called about the fridge",
		status: "filler",
		target: "fridge",
		target_filename: "PICTURE_138.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "singer",
		Distractor1_filename: "PICTURE_131.png",
		Distractor2: "present",
		Distractor2_filename: "PICTURE_338.png",
		Distractor3: "caterpillar",
		Distractor3_filename: "PICTURE_561.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_fridge_1_AnF.wav"
	},
	unpred_frog: {
		index: "79",
		trial_code: "unpred_frog",
		sentence: "He should know about the frog",
		status: "filler",
		target: "frog",
		target_filename: "PICTURE_612.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "glass",
		Distractor1_filename: "PICTURE_142.png",
		Distractor2: "monster",
		Distractor2_filename: "PICTURE_337.png",
		Distractor3: "watermelon",
		Distractor3_filename: "PICTURE_560.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_frog_1_AnF.wav"
	},
	unpred_glasses: {
		index: "80",
		trial_code: "unpred_glasses",
		sentence: "Nancy didn't discuss the glasses",
		status: "filler",
		target: "glasses",
		target_filename: "PICTURE_733.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "corner",
		Distractor1_filename: "PICTURE_124.png",
		Distractor2: "owl",
		Distractor2_filename: "PICTURE_323.png",
		Distractor3: "breakfast",
		Distractor3_filename: "PICTURE_555.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_glasses_1_AnF.wav"
	},
	unpred_gun: {
		index: "81",
		trial_code: "unpred_gun",
		sentence: "They heard I called about the gun",
		status: "filler",
		target: "gun",
		target_filename: "PICTURE_461.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "salad",
		Distractor1_filename: "PICTURE_191.png",
		Distractor2: "purse",
		Distractor2_filename: "PICTURE_388.png",
		Distractor3: "umbrella",
		Distractor3_filename: "PICTURE_653.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_gun_1_AnF.wav"
	},
	unpred_harp: {
		index: "82",
		trial_code: "unpred_harp",
		sentence: "Nancy had considered the harp",
		status: "filler",
		target: "harp",
		target_filename: "PICTURE_605.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "keyhole",
		Distractor1_filename: "PICTURE_149.png",
		Distractor2: "bell pepper",
		Distractor2_filename: "PICTURE_348.png",
		Distractor3: "gloves",
		Distractor3_filename: "PICTURE_576.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_harp_1_AnF.wav"
	},
	unpred_hotdog: {
		index: "83",
		trial_code: "unpred_hotdog",
		sentence: "He would think about the hot dog",
		status: "filler",
		target: "hot dog",
		target_filename: "PICTURE_627.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "wound",
		Distractor1_filename: "PICTURE_118.png",
		Distractor2: "perfume",
		Distractor2_filename: "PICTURE_314.png",
		Distractor3: "bat",
		Distractor3_filename: "PICTURE_547.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_hotdog_1_AnF.wav"
	},
	unpred_house: {
		index: "84",
		trial_code: "unpred_house",
		sentence: "He wants to talk about the house",
		status: "filler",
		target: "house",
		target_filename: "PICTURE_522.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "boomerang",
		Distractor1_filename: "PICTURE_209.png",
		Distractor2: "cauliflower",
		Distractor2_filename: "PICTURE_373.png",
		Distractor3: "koala",
		Distractor3_filename: "PICTURE_601.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_house_2_AnF.wav"
	},
	unpred_iceberg: {
		index: "85",
		trial_code: "unpred_iceberg",
		sentence: "Bill hopes Paul heard about the iceberg",
		status: "filler",
		target: "iceberg",
		target_filename: "PICTURE_577.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "domino",
		Distractor1_filename: "PICTURE_154.png",
		Distractor2: "guitar",
		Distractor2_filename: "PICTURE_357.png",
		Distractor3: "corn",
		Distractor3_filename: "PICTURE_587.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_iceberg_2_AnF.wav"
	},
	unpred_kite: {
		index: "86",
		trial_code: "unpred_kite",
		sentence: "We heard they called about the kite",
		status: "filler",
		target: "kite",
		target_filename: "PICTURE_720.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "shoelace",
		Distractor1_filename: "PICTURE_167.png",
		Distractor2: "whale",
		Distractor2_filename: "PICTURE_724.png",
		Distractor3: "funnel",
		Distractor3_filename: "PICTURE_633.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_kite_1_AnF.wav"
	},
	unpred_lighter: {
		index: "87",
		trial_code: "unpred_lighter",
		sentence: "You're glad they heard about the lighter",
		status: "filler",
		target: "lighter",
		target_filename: "PICTURE_558.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "wheelbarrow",
		Distractor1_filename: "PICTURE_160.png",
		Distractor2: "dolphin",
		Distractor2_filename: "PICTURE_361.png",
		Distractor3: "sled",
		Distractor3_filename: "PICTURE_625.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_lighter_2_AnF.wav"
	},
	unpred_magnet: {
		index: "88",
		trial_code: "unpred_magnet",
		sentence: "Tom discussed the magnet",
		status: "filler",
		target: "magnet",
		target_filename: "PICTURE_571.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "snail",
		Distractor1_filename: "PICTURE_152.png",
		Distractor2: "goat",
		Distractor2_filename: "PICTURE_354.png",
		Distractor3: "lab",
		Distractor3_filename: "PICTURE_582.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_magnet_2_AnF.wav"
	},
	unpred_painter: {
		index: "89",
		trial_code: "unpred_painter",
		sentence: "We have discussed the painter",
		status: "filler",
		target: "painter",
		target_filename: "PICTURE_175.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "witch",
		Distractor1_filename: "PICTURE_184.png",
		Distractor2: "dragonfly",
		Distractor2_filename: "PICTURE_404.png",
		Distractor3: "airport",
		Distractor3_filename: "PICTURE_617.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_painter_2_AnF.wav"
	},
	unpred_piano: {
		index: "90",
		trial_code: "unpred_piano",
		sentence: "She hears Bob asked about the piano",
		status: "filler",
		target: "piano",
		target_filename: "PICTURE_626.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "horse",
		Distractor1_filename: "PICTURE_117.png",
		Distractor2: "barber",
		Distractor2_filename: "PICTURE_313.png",
		Distractor3: "Apple",
		Distractor3_filename: "PICTURE_552.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_piano_1_AnF.wav"
	},
	unpred_plant: {
		index: "91",
		trial_code: "unpred_plant",
		sentence: "I'm glad you heard about the plant",
		status: "filler",
		target: "plant",
		target_filename: "PICTURE_611.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "trash can",
		Distractor1_filename: "PICTURE_145.png",
		Distractor2: "flipper",
		Distractor2_filename: "PICTURE_341.png",
		Distractor3: "beak",
		Distractor3_filename: "PICTURE_575.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_plant_1_AnF.wav"
	},
	unpred_prison: {
		index: "92",
		trial_code: "unpred_prison",
		sentence: "I had not thought about the prison",
		status: "filler",
		target: "prison",
		target_filename: "PICTURE_623.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "olive",
		Distractor1_filename: "PICTURE_146.png",
		Distractor2: "ruler",
		Distractor2_filename: "PICTURE_336.png",
		Distractor3: "bull",
		Distractor3_filename: "PICTURE_570.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_prison_2_AnF.wav"
	},
	unpred_pumpkin: {
		index: "93",
		trial_code: "unpred_pumpkin",
		sentence: "I've spoken about the pumpkin",
		status: "filler",
		target: "pumpkin",
		target_filename: "PICTURE_551.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "alligator",
		Distractor1_filename: "PICTURE_189.png",
		Distractor2: "fan",
		Distractor2_filename: "PICTURE_368.png",
		Distractor3: "towel",
		Distractor3_filename: "PICTURE_591.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_pumpkin_2_AnF.wav"
	},
	unpred_rifle: {
		index: "94",
		trial_code: "unpred_rifle",
		sentence: "Bill might discuss the rifle",
		status: "filler",
		target: "rifle",
		target_filename: "PICTURE_645.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "sack",
		Distractor1_filename: "PICTURE_127.png",
		Distractor2: "cow",
		Distractor2_filename: "PICTURE_319.png",
		Distractor3: "bracelet",
		Distractor3_filename: "PICTURE_588.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_rifle_2_AnF.wav"
	},
	unpred_scar: {
		index: "95",
		trial_code: "unpred_scar",
		sentence: "The boy can't talk about the scar",
		status: "filler",
		target: "scar",
		target_filename: "PICTURE_207.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "lemon",
		Distractor1_filename: "PICTURE_129.png",
		Distractor2: "UFO",
		Distractor2_filename: "PICTURE_315.png",
		Distractor3: "puppet",
		Distractor3_filename: "PICTURE_554.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_scar_1_AnF.wav"
	},
	unpred_shirt: {
		index: "96",
		trial_code: "unpred_shirt",
		sentence: "They had a problem with the shirt",
		status: "filler",
		target: "shirt",
		target_filename: "PICTURE_353.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "ghost",
		Distractor1_filename: "PICTURE_139.png",
		Distractor2: "helmet",
		Distractor2_filename: "PICTURE_327.png",
		Distractor3: "wolf",
		Distractor3_filename: "PICTURE_557.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_shirt_1_AnF.wav"
	},
	unpred_snow: {
		index: "97",
		trial_code: "unpred_snow",
		sentence: "She hopes Jane called about the snow",
		status: "filler",
		target: "snow",
		target_filename: "PICTURE_390.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "triangle",
		Distractor1_filename: "PICTURE_181.png",
		Distractor2: "anchor",
		Distractor2_filename: "PICTURE_405.png",
		Distractor3: "honey",
		Distractor3_filename: "PICTURE_610.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_snow_1_AnF.wav"
	},
	unpred_soldier: {
		index: "98",
		trial_code: "unpred_soldier",
		sentence: "The man would not discuss the soldier",
		status: "filler",
		target: "soldier",
		target_filename: "PICTURE_317.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "pipe",
		Distractor1_filename: "PICTURE_148.png",
		Distractor2: "bible",
		Distractor2_filename: "PICTURE_350.png",
		Distractor3: "eggplant",
		Distractor3_filename: "PICTURE_573.png",
		audio_tag: "2",
		audio_filename: "AnF/unpred_soldier_2_AnF.wav"
	},
	unpred_submarine: {
		index: "99",
		trial_code: "unpred_submarine",
		sentence: "She has known about the submarine",
		status: "filler",
		target: "submarine",
		target_filename: "PICTURE_514.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "back",
		Distractor1_filename: "PICTURE_169.png",
		Distractor2: "lobster",
		Distractor2_filename: "PICTURE_378.png",
		Distractor3: "cube",
		Distractor3_filename: "PICTURE_595.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_submarine_1_AnF.wav"
	},
	unpred_tattoo: {
		index: "100",
		trial_code: "unpred_tattoo",
		sentence: "Bill cannot consider the tattoo",
		status: "filler",
		target: "tattoo",
		target_filename: "PICTURE_413.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "mushroom",
		Distractor1_filename: "PICTURE_177.png",
		Distractor2: "ballerina",
		Distractor2_filename: "PICTURE_399.png",
		Distractor3: "pencil case",
		Distractor3_filename: "PICTURE_609.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_tattoo_1_AnF.wav"
	},
	unpred_telescope: {
		index: "101",
		trial_code: "unpred_telescope",
		sentence: "Bob has discussed the telescope",
		status: "filler",
		target: "telescope",
		target_filename: "PICTURE_699.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "kiwi",
		Distractor1_filename: "PICTURE_125.png",
		Distractor2: "bra",
		Distractor2_filename: "PICTURE_331.png",
		Distractor3: "snake",
		Distractor3_filename: "PICTURE_549.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_telescope_1_AnF.wav"
	},
	unpred_toaster: {
		index: "102",
		trial_code: "unpred_toaster",
		sentence: "She's glad Jane asked about the toaster",
		status: "filler",
		target: "toaster",
		target_filename: "PICTURE_562.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "cigarette",
		Distractor1_filename: "PICTURE_153.png",
		Distractor2: "spear",
		Distractor2_filename: "PICTURE_367.png",
		Distractor3: "elephant",
		Distractor3_filename: "PICTURE_579.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_toaster_1_AnF.wav"
	},
	unpred_tree: {
		index: "103",
		trial_code: "unpred_tree",
		sentence: "Ruth hopes he heard about the tree",
		status: "filler",
		target: "tree",
		target_filename: "PICTURE_693.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "parachute",
		Distractor1_filename: "PICTURE_126.png",
		Distractor2: "butter",
		Distractor2_filename: "PICTURE_335.png",
		Distractor3: "syringe",
		Distractor3_filename: "PICTURE_594.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_tree_1_AnF.wav"
	},
	unpred_zebra: {
		index: "104",
		trial_code: "unpred_zebra",
		sentence: "The class is discussing the zebra",
		status: "filler",
		target: "zebra",
		target_filename: "PICTURE_379.png",
		competitor: "NA",
		competitor_filename: "NA",
		Distractor1: "recorder",
		Distractor1_filename: "PICTURE_156.png",
		Distractor2: "pot",
		Distractor2_filename: "PICTURE_369.png",
		Distractor3: "iron",
		Distractor3_filename: "PICTURE_586.png",
		audio_tag: "1",
		audio_filename: "AnF/unpred_zebra_1_AnF.wav"
	}
}